"""add_dynamic_payment_methods

Revision ID: 187244d8aadc
Revises: 0ea1168a33e8
Create Date: 2026-05-01 23:28:21.130323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '187244d8aadc'
down_revision: Union[str, Sequence[str], None] = '0ea1168a33e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method_configs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_payment_method_configs_id'), 'payment_method_configs', ['id'], unique=False)
    op.create_index(op.f('ix_payment_method_configs_name'), 'payment_method_configs', ['name'], unique=True)
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('CASH', 'CARD', 'TRANSFER', 'MIXED', name='paymentmethod'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('work_order_payments', 'payment_method',
               existing_type=postgresql.ENUM('CASH', 'CARD', 'TRANSFER', 'MIXED', name='paymentmethod'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_order_payments', 'payment_method',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CASH', 'CARD', 'TRANSFER', 'MIXED', name='paymentmethod'),
               existing_nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CASH', 'CARD', 'TRANSFER', 'MIXED', name='paymentmethod'),
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_method_configs_name'), table_name='payment_method_configs')
    op.drop_index(op.f('ix_payment_method_configs_id'), table_name='payment_method_configs')
    op.drop_table('payment_method_configs')
    # ### end Alembic commands ###
