"""fix_product_categories_unique_per_company

Revision ID: 1b5e346e3a0f
Revises: 698247d7fa86
Create Date: 2026-05-26 05:21:28.591498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5e346e3a0f'
down_revision: Union[str, Sequence[str], None] = '698247d7fa86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_payment_method_configs_name;')
    op.create_index(op.f('ix_payment_method_configs_name'), 'payment_method_configs', ['name'], unique=False)
    op.execute('ALTER TABLE product_categories DROP CONSTRAINT IF EXISTS product_categories_name_key;')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_unique_constraint('uix_category_name_company_parent', 'product_categories', ['name', 'company_id', 'parent_id'])
    op.drop_constraint(op.f('users_branch_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_branch_id_fkey'), 'users', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uix_category_name_company_parent', 'product_categories', type_='unique')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_unique_constraint(op.f('product_categories_name_key'), 'product_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payment_method_configs_name'), table_name='payment_method_configs')
    # ### end Alembic commands ###
