"""remove_product_name_unique_and_others

Revision ID: 5c26c0a6761b
Revises: e1307ce9cc68
Create Date: 2026-05-26 10:03:03.064398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c26c0a6761b'
down_revision: Union[str, Sequence[str], None] = 'e1307ce9cc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE payment_method_configs DROP CONSTRAINT IF EXISTS payment_method_configs_key_key;')
    op.create_unique_constraint('uix_payment_method_company_key', 'payment_method_configs', ['company_id', 'key'])
    op.execute('DROP INDEX IF EXISTS ix_products_name;')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_payment_method_company_key', 'payment_method_configs', type_='unique')
    op.create_unique_constraint(op.f('payment_method_configs_key_key'), 'payment_method_configs', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
