"""tenant_architecture

Revision ID: 698247d7fa86
Revises: 7263f2345322
Create Date: 2026-05-05 23:17:17.109822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698247d7fa86'
down_revision: Union[str, Sequence[str], None] = '7263f2345322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.add_column('branches', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_foreign_key(None, 'branches', 'companies', ['company_id'], ['id'])
    op.add_column('cash_registers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cash_registers_company_id'), 'cash_registers', ['company_id'], unique=False)
    op.create_foreign_key(None, 'cash_registers', 'companies', ['company_id'], ['id'])
    op.add_column('cash_sessions', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cash_sessions_company_id'), 'cash_sessions', ['company_id'], unique=False)
    op.create_foreign_key(None, 'cash_sessions', 'companies', ['company_id'], ['id'])
    op.add_column('customers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.add_column('expense_categories', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expense_categories_company_id'), 'expense_categories', ['company_id'], unique=False)
    op.create_foreign_key(None, 'expense_categories', 'companies', ['company_id'], ['id'])
    op.add_column('expenses', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expenses_company_id'), 'expenses', ['company_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'companies', ['company_id'], ['id'])
    op.add_column('inventory_movement_items', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inventory_movement_items_company_id'), 'inventory_movement_items', ['company_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movement_items', 'companies', ['company_id'], ['id'])
    op.add_column('inventory_movements', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inventory_movements_company_id'), 'inventory_movements', ['company_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'companies', ['company_id'], ['id'])
    op.add_column('payment_method_configs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payment_method_configs_company_id'), 'payment_method_configs', ['company_id'], unique=False)
    op.create_foreign_key(None, 'payment_method_configs', 'companies', ['company_id'], ['id'])
    op.add_column('payments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'])
    op.add_column('product_categories', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_product_categories_company_id'), 'product_categories', ['company_id'], unique=False)
    op.create_foreign_key(None, 'product_categories', 'companies', ['company_id'], ['id'])
    op.add_column('products', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.add_column('purchase_items', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchase_items_company_id'), 'purchase_items', ['company_id'], unique=False)
    op.create_foreign_key(None, 'purchase_items', 'companies', ['company_id'], ['id'])
    op.add_column('purchases', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchases_company_id'), 'purchases', ['company_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'companies', ['company_id'], ['id'])
    op.add_column('quote_items', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quote_items_company_id'), 'quote_items', ['company_id'], unique=False)
    op.create_foreign_key(None, 'quote_items', 'companies', ['company_id'], ['id'])
    op.add_column('quotes', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quotes_company_id'), 'quotes', ['company_id'], unique=False)
    op.create_foreign_key(None, 'quotes', 'companies', ['company_id'], ['id'])
    op.add_column('sale_items', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sale_items_company_id'), 'sale_items', ['company_id'], unique=False)
    op.create_foreign_key(None, 'sale_items', 'companies', ['company_id'], ['id'])
    op.add_column('storage_locations', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_storage_locations_company_id'), 'storage_locations', ['company_id'], unique=False)
    op.create_foreign_key(None, 'storage_locations', 'companies', ['company_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.add_column('tickets', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tickets_company_id'), 'tickets', ['company_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'companies', ['company_id'], ['id'])
    op.add_column('user_branch_access', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_user_branch_access_company_id'), 'user_branch_access', ['company_id'], unique=False)
    op.create_foreign_key(None, 'user_branch_access', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.add_column('vehicles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'companies', ['company_id'], ['id'])
    op.add_column('work_order_items', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_work_order_items_company_id'), 'work_order_items', ['company_id'], unique=False)
    op.create_foreign_key(None, 'work_order_items', 'companies', ['company_id'], ['id'])
    op.add_column('work_order_payments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_work_order_payments_company_id'), 'work_order_payments', ['company_id'], unique=False)
    op.create_foreign_key(None, 'work_order_payments', 'companies', ['company_id'], ['id'])
    op.add_column('work_orders', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_work_orders_company_id'), 'work_orders', ['company_id'], unique=False)
    op.create_foreign_key(None, 'work_orders', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_company_id'), table_name='work_orders')
    op.drop_column('work_orders', 'company_id')
    op.drop_constraint(None, 'work_order_payments', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_payments_company_id'), table_name='work_order_payments')
    op.drop_column('work_order_payments', 'company_id')
    op.drop_constraint(None, 'work_order_items', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_items_company_id'), table_name='work_order_items')
    op.drop_column('work_order_items', 'company_id')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_column('vehicles', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'user_branch_access', type_='foreignkey')
    op.drop_index(op.f('ix_user_branch_access_company_id'), table_name='user_branch_access')
    op.drop_column('user_branch_access', 'company_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_company_id'), table_name='tickets')
    op.drop_column('tickets', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'storage_locations', type_='foreignkey')
    op.drop_index(op.f('ix_storage_locations_company_id'), table_name='storage_locations')
    op.drop_column('storage_locations', 'company_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_company_id'), table_name='sale_items')
    op.drop_column('sale_items', 'company_id')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_quotes_company_id'), table_name='quotes')
    op.drop_column('quotes', 'company_id')
    op.drop_constraint(None, 'quote_items', type_='foreignkey')
    op.drop_index(op.f('ix_quote_items_company_id'), table_name='quote_items')
    op.drop_column('quote_items', 'company_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_company_id'), table_name='purchases')
    op.drop_column('purchases', 'company_id')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_items_company_id'), table_name='purchase_items')
    op.drop_column('purchase_items', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_index(op.f('ix_product_categories_company_id'), table_name='product_categories')
    op.drop_column('product_categories', 'company_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_column('payments', 'company_id')
    op.drop_constraint(None, 'payment_method_configs', type_='foreignkey')
    op.drop_index(op.f('ix_payment_method_configs_company_id'), table_name='payment_method_configs')
    op.drop_column('payment_method_configs', 'company_id')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_company_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'company_id')
    op.drop_constraint(None, 'inventory_movement_items', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movement_items_company_id'), table_name='inventory_movement_items')
    op.drop_column('inventory_movement_items', 'company_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_company_id'), table_name='expenses')
    op.drop_column('expenses', 'company_id')
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.drop_index(op.f('ix_expense_categories_company_id'), table_name='expense_categories')
    op.drop_column('expense_categories', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_column('customers', 'company_id')
    op.drop_constraint(None, 'cash_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_cash_sessions_company_id'), table_name='cash_sessions')
    op.drop_column('cash_sessions', 'company_id')
    op.drop_constraint(None, 'cash_registers', type_='foreignkey')
    op.drop_index(op.f('ix_cash_registers_company_id'), table_name='cash_registers')
    op.drop_column('cash_registers', 'company_id')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_column('branches', 'company_id')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
