"""multi_branch_architecture

Revision ID: 70b16041ece4
Revises: 71b5b8c9e067
Create Date: 2026-04-30 02:05:56.928087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b16041ece4'
down_revision: Union[str, Sequence[str], None] = '71b5b8c9e067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_table('user_branch_access',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_branch_access_id'), 'user_branch_access', ['id'], unique=False)
    op.create_index(op.f('ix_user_branch_access_user_id'), 'user_branch_access', ['user_id'], unique=False)
    op.add_column('cash_registers', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cash_registers', 'branches', ['branch_id'], ['id'])
    op.add_column('products', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'branches', ['branch_id'], ['id'])
    op.add_column('purchases', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchases_invoice_number'), 'purchases', ['invoice_number'], unique=False)
    op.create_foreign_key(None, 'purchases', 'branches', ['branch_id'], ['id'])
    op.add_column('quotes', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'branches', ['branch_id'], ['id'])
    op.add_column('storage_locations', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'storage_locations', 'branches', ['branch_id'], ['id'])
    op.add_column('tickets', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'branches', ['branch_id'], ['id'])
    op.add_column('work_orders', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'work_orders', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'branch_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'branch_id')
    op.drop_constraint(None, 'storage_locations', type_='foreignkey')
    op.drop_column('storage_locations', 'branch_id')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'branch_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_invoice_number'), table_name='purchases')
    op.drop_column('purchases', 'branch_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'branch_id')
    op.drop_constraint(None, 'cash_registers', type_='foreignkey')
    op.drop_column('cash_registers', 'branch_id')
    op.drop_index(op.f('ix_user_branch_access_user_id'), table_name='user_branch_access')
    op.drop_index(op.f('ix_user_branch_access_id'), table_name='user_branch_access')
    op.drop_table('user_branch_access')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
