"""quotes_variable_consumption

Revision ID: 71b5b8c9e067
Revises: ef7ebd5d3371
Create Date: 2026-04-18 13:00:34.744866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b5b8c9e067'
down_revision: Union[str, Sequence[str], None] = 'ef7ebd5d3371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_items', sa.Column('consumption_rate', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('quote_items', sa.Column('stock_reduced', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('work_order_items', sa.Column('consumption_rate', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('work_order_items', sa.Column('stock_reduced', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_items', 'stock_reduced')
    op.drop_column('work_order_items', 'consumption_rate')
    op.drop_column('quote_items', 'stock_reduced')
    op.drop_column('quote_items', 'consumption_rate')
    # ### end Alembic commands ###
