"""add branch_id to users

Revision ID: 7263f2345322
Revises: 187244d8aadc
Create Date: 2026-05-05 01:40:18.314449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7263f2345322'
down_revision: Union[str, Sequence[str], None] = '187244d8aadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('purchase_category', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('mileage', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    op.add_column('work_order_items', sa.Column('done', sa.Boolean(), nullable=False))
    op.add_column('work_order_items', sa.Column('stock_consumed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_items', 'stock_consumed')
    op.drop_column('work_order_items', 'done')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.drop_column('quotes', 'mileage')
    op.drop_column('purchases', 'purchase_category')
    # ### end Alembic commands ###
