"""Add product_suppliers table

Revision ID: e1307ce9cc68
Revises: 1b5e346e3a0f
Create Date: 2026-05-26 07:28:28.645503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1307ce9cc68'
down_revision: Union[str, Sequence[str], None] = '1b5e346e3a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_suppliers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'supplier_id', 'supplier_code', name='uix_product_supplier_code')
    )
    op.create_index(op.f('ix_product_suppliers_company_id'), 'product_suppliers', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_suppliers_id'), 'product_suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_product_suppliers_supplier_code'), 'product_suppliers', ['supplier_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_suppliers_supplier_code'), table_name='product_suppliers')
    op.drop_index(op.f('ix_product_suppliers_id'), table_name='product_suppliers')
    op.drop_index(op.f('ix_product_suppliers_company_id'), table_name='product_suppliers')
    op.drop_table('product_suppliers')
    # ### end Alembic commands ###
