"""variable_consumption

Revision ID: ef7ebd5d3371
Revises: 7ee96eb47c1d
Create Date: 2026-04-18 12:54:27.598647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7ebd5d3371'
down_revision: Union[str, Sequence[str], None] = '7ee96eb47c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_variable_consumption', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('default_consumption_rate', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('sale_items', sa.Column('consumption_rate', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('sale_items', sa.Column('stock_reduced', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'stock_reduced')
    op.drop_column('sale_items', 'consumption_rate')
    op.drop_column('products', 'default_consumption_rate')
    op.drop_column('products', 'is_variable_consumption')
    # ### end Alembic commands ###
